### ISSUE TITLE
Unhandled Exception: Request too large

### ISSUE THREAD

**Issue by Cronium** [ddevault/srutils#2]
Restoring image: footer-bg.png

Unhandled Exception: System.Net.WebException: The remote server returned an erro
r: (413) Request Entity Too Large.
   at System.Net.HttpWebRequest.GetResponse()
   at RedditSharp.SubredditStyle.UploadImage(String name, ImageType imageType, B
yte[] file)
   at srutil.Restore.Execute(String[] args, Reddit reddit)
   at srutil.Program.Main(String[] args)

**Comment by Cronium** [comment]
This was while attempting to restore to a subreddit "lol.zip" a backup of /r/leagueoflegends

**Comment by ddevault** [comment]
Ouch, that's a difficult one to solve. After converting to PNGs, Reddit may actually increase the size of the image beyond acceptable boundaries, on its own servers. Open up the backup zip and compress the image.

Closing this issue as unsolvable.
